import {useEffect,useMemo,useState} from 'react';
import {askKnowledge,getEquipment,getSummary,getTree,getTwin,uploadData,uploadKnowledge} from '../../services/api';
import type {Equipment,RagAnswer,Summary,TreeNode,Twin} from '../../types/domain';
import {MetricCard} from '../../components/MetricCard'; import {Tree} from '../../components/Tree';
const tabs=['Overview','Equipment twin','SAP imports','AI knowledge'] as const;
export function Dashboard(){
 const[s,setS]=useState<Summary|null>(null),[e,setE]=useState<Equipment[]>([]),[t,setT]=useState<TreeNode[]>([]),[selected,setSelected]=useState(''),[twin,setTwin]=useState<Twin|null>(null),[tab,setTab]=useState<(typeof tabs)[number]>('Overview'),[err,setErr]=useState(''),[busy,setBusy]=useState(''),[question,setQuestion]=useState(''),[rag,setRag]=useState<RagAnswer|null>(null),[docType,setDocType]=useState('MANUAL');
 async function refresh(){try{setErr('');const[a,b,c]=await Promise.all([getSummary(),getEquipment(),getTree()]);setS(a);setE(b);setT(c);if(!selected&&b[0])setSelected(b[0].id)}catch{setErr('API is not reachable. Start Docker Compose and refresh.')}}
 useEffect(()=>{refresh()},[]); useEffect(()=>{if(selected)getTwin(selected).then(setTwin).catch(()=>setTwin(null))},[selected]); const current=useMemo(()=>e.find(x=>x.id===selected),[e,selected]);
 async function upload(ev:React.ChangeEvent<HTMLInputElement>,kind:string){const f=ev.target.files?.[0];if(!f)return;try{setBusy(kind);const r=await uploadData(f,kind);setErr(`Imported ${r.rows_created} rows; skipped ${r.rows_skipped}.`);await refresh()}catch(x:any){setErr(x?.response?.data?.detail||'Import failed')}finally{setBusy('');ev.target.value=''}}
 async function knowledgeUpload(ev:React.ChangeEvent<HTMLInputElement>){const f=ev.target.files?.[0];if(!f)return;try{setBusy('knowledge');const r=await uploadKnowledge(f,docType,current?.equipment_number);setErr(`Imported ${r.chunks} knowledge chunks for retrieval.`)}catch(x:any){setErr(x?.response?.data?.detail||'Knowledge import failed')}finally{setBusy('');ev.target.value=''}}
 async function ask(){if(!question.trim())return;try{setBusy('ask');setRag(await askKnowledge(question,selected))}catch(x:any){setErr(x?.response?.data?.detail||'Question failed')}finally{setBusy('')}}
 return <div className="shell"><header><div><div className="eyebrow">RELIABILITY INTELLIGENCE</div><h1>Reliability Twin</h1><p>Actual condition · change history · failure learning · SAP-ready</p></div><div className="live"><i/>Data foundation online</div></header><nav>{tabs.map(x=><button className={tab===x?'active':''} onClick={()=>setTab(x)} key={x}>{x}</button>)}</nav>{err&&<div className={err.startsWith('Imported')?'notice':'error'}>{err}</div>}
 {tab==='Overview'&&<><section className="metrics"><MetricCard label="Mapped equipment" value={s?.equipment_count??'—'}/><MetricCard label="Fleet availability" value={s?`${s.average_availability}%`:'—'}/><MetricCard label="Reliability score" value={s?s.average_reliability:'—'}/><MetricCard label="High-risk assets" value={s?.high_risk_count??'—'}/></section><main><section className="panel"><div className="panel-head"><h2>Plant hierarchy</h2><p>Functional location → equipment → sub-equipment</p></div>{t.length?<Tree nodes={t}/>:<div className="empty">Import your SAP hierarchy to begin.</div>}</section><section className="panel"><div className="panel-head"><h2>Attention queue</h2><p>Planner view, ordered by equipment criticality</p></div>{e.slice(0,30).map(x=><button className="equipment-row" key={x.id} onClick={()=>{setSelected(x.id);setTab('Equipment twin')}}><span>{x.equipment_number||'—'}</span><strong>{x.name}</strong><b className="pill">{x.status}</b></button>)}{!e.length&&<div className="empty">No equipment mapped.</div>}</section></main></>}
 {tab==='Equipment twin'&&<section className="workspace"><aside className="panel equipment-list"><div className="panel-head"><h2>Equipment</h2></div>{e.map(x=><button className={selected===x.id?'selected':''} onClick={()=>setSelected(x.id)} key={x.id}><small>{x.equipment_number}</small>{x.name}</button>)}</aside><section className="panel twin"><div className="panel-head"><h2>{current?.name||'Select equipment'}</h2><p>{current?.equipment_number} · {current?.criticality||'Criticality not set'} · {current?.status}</p></div><h3>Actual condition</h3><div className="parameter-grid">{twin?.parameters.map(p=><article key={p.parameter_id}><small>{p.name}</small><strong>{p.latest?.value??'—'} {p.unit}</strong><span>{p.latest?.timestamp?new Date(p.latest.timestamp).toLocaleString():'No reading'}</span></article>)}{!twin?.parameters.length&&<div className="empty">No condition parameters imported.</div>}</div><h3>Component change history</h3>{twin?.component_changes.map((x:any)=><div className="history" key={x.id}><time>{new Date(x.changed_at).toLocaleDateString()}</time><strong>{x.component_name}</strong><span>{x.reason||'Reason not recorded'}</span></div>)}{!twin?.component_changes.length&&<div className="empty">No component changes recorded.</div>}</section></section>}
 {tab==='SAP imports'&&<section className="panel import-page"><div className="panel-head"><h2>Import SAP HANA exports</h2><p>Excel is validated against equipment number. Unmapped rows are reported, never silently guessed.</p></div><div className="import-grid">{[['hierarchy','Equipment hierarchy','Functional locations and equipment master'],['condition','Condition readings','Measuring points, values and timestamps'],['maintenance','Maintenance history','Orders, work performed, dates and downtime'],['failure','Failure history','Notifications, causes, breakdowns and downtime'],['changes','Component changes','Replacement history, reason and SAP order']].map(([k,title,d])=><label className="import-card" key={k}><b>{title}</b><span>{d}</span><em>{busy===k?'Importing…':'Choose Excel file'}</em><input hidden type="file" accept=".xlsx,.xls" onChange={x=>upload(x,k)}/></label>)}</div></section>}
 {tab==='AI knowledge'&&<section className="panel ai"><div className="panel-head"><h2>Plant Reliability Copilot</h2><p>Selected scope: {current?.equipment_number||'choose equipment'} · {current?.name||'none'}</p></div><div className="ai-tools"><div className="knowledge-upload"><select value={docType} onChange={x=>setDocType(x.target.value)}><option>MANUAL</option><option>DRAWING</option><option>FMEA</option><option>RCA</option><option>HISTORY_CARD</option><option>SOP</option><option>DATASHEET</option></select><label>{busy==='knowledge'?'Indexing…':'Import knowledge file'}<input hidden type="file" accept=".pdf,.docx,.xlsx,.xls,.csv,.txt,.md" onChange={knowledgeUpload}/></label></div><div className="askbox"><textarea value={question} onChange={x=>setQuestion(x.target.value)} placeholder="Ask about condition, repeated failures, component history or recommended checks…"/><button onClick={ask} disabled={busy==='ask'}>{busy==='ask'?'Checking evidence…':'Ask with evidence'}</button></div>{rag&&<div className="answer"><div className={`model-state ${rag.model_status}`}>AI: {rag.model_status} · Retrieval: {rag.retrieval_mode}</div><p>{rag.answer}</p><h3>Sources</h3>{rag.sources.map(s=><details key={s.source_id}><summary>[{s.source_id}] {s.title} · {s.document_type}</summary><p>{s.excerpt}</p></details>)}</div>}</div></section>}
 <footer>v0.2 · PostgreSQL + pgvector · FastAPI · React TypeScript · provider-neutral AI</footer></div>}
