import uuid
from datetime import datetime
from sqlalchemy import Column,String,Integer,Float,Boolean,Date,DateTime,Text,ForeignKey,BigInteger
from sqlalchemy.dialects.postgresql import UUID,JSONB
from sqlalchemy.orm import declarative_base
from pgvector.sqlalchemy import Vector
Base=declarative_base()
class Plant(Base):
 __tablename__='plants'; id=Column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4); code=Column(String(50),unique=True,nullable=False); name=Column(String(255),nullable=False); description=Column(Text); created_at=Column(DateTime(timezone=True),default=datetime.utcnow)
class FunctionalLocation(Base):
 __tablename__='functional_locations'; id=Column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4); plant_id=Column(UUID(as_uuid=True),ForeignKey('plants.id')); parent_id=Column(UUID(as_uuid=True),ForeignKey('functional_locations.id')); code=Column(String(255),unique=True,nullable=False); name=Column(String(255)); description=Column(Text); level=Column(Integer,default=0); source=Column(String(50),default='manual'); created_at=Column(DateTime(timezone=True),default=datetime.utcnow)
class Equipment(Base):
 __tablename__='equipment'; id=Column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4); equipment_number=Column(String(100),unique=True); functional_location_id=Column(UUID(as_uuid=True),ForeignKey('functional_locations.id')); parent_equipment_id=Column(UUID(as_uuid=True),ForeignKey('equipment.id')); name=Column(String(255),nullable=False); equipment_type=Column(String(100)); manufacturer=Column(String(255)); model=Column(String(255)); serial_number=Column(String(255)); installation_date=Column(Date); commissioning_date=Column(Date); criticality=Column(String(20)); status=Column(String(50),default='UNKNOWN'); metadata_json=Column("metadata", JSONB, default=dict); created_at=Column(DateTime(timezone=True),default=datetime.utcnow); updated_at=Column(DateTime(timezone=True),default=datetime.utcnow)
class Parameter(Base):
 __tablename__='parameters'; id=Column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4); equipment_id=Column(UUID(as_uuid=True),ForeignKey('equipment.id',ondelete='CASCADE'),nullable=False); parameter_code=Column(String(100),nullable=False); name=Column(String(255),nullable=False); unit=Column(String(50)); data_type=Column(String(30),default='numeric'); normal_min=Column(Float); normal_max=Column(Float); warning_min=Column(Float); warning_max=Column(Float); critical_min=Column(Float); critical_max=Column(Float); source=Column(String(50)); created_at=Column(DateTime(timezone=True),default=datetime.utcnow)
class ConditionReading(Base):
 __tablename__='condition_readings'; id=Column(BigInteger,primary_key=True); parameter_id=Column(UUID(as_uuid=True),ForeignKey('parameters.id',ondelete='CASCADE'),nullable=False); timestamp=Column(DateTime(timezone=True),nullable=False); value=Column(Float); quality=Column(String(30),default='GOOD'); source=Column(String(50)); metadata_json=Column("metadata", JSONB, default=dict)
class MaintenanceEvent(Base):
 __tablename__='maintenance_events'; id=Column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4); equipment_id=Column(UUID(as_uuid=True),ForeignKey('equipment.id')); sap_order_number=Column(String(100)); event_type=Column(String(50)); title=Column(String(500)); description=Column(Text); planned_start=Column(DateTime(timezone=True)); actual_start=Column(DateTime(timezone=True)); actual_end=Column(DateTime(timezone=True)); downtime_hours=Column(Float); maintenance_team=Column(String(255)); cost=Column(Float); source=Column(String(50),default='manual'); created_at=Column(DateTime(timezone=True),default=datetime.utcnow)
class Failure(Base):
 __tablename__='failures'; id=Column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4); equipment_id=Column(UUID(as_uuid=True),ForeignKey('equipment.id')); notification_number=Column(String(100)); failure_start=Column(DateTime(timezone=True)); failure_end=Column(DateTime(timezone=True)); failure_mode=Column(String(255)); failure_cause=Column(String(255)); damage_code=Column(String(100)); cause_code=Column(String(100)); activity_code=Column(String(100)); description=Column(Text); breakdown=Column(Boolean,default=False); downtime_hours=Column(Float); created_at=Column(DateTime(timezone=True),default=datetime.utcnow)
class ReliabilityMetric(Base):
 __tablename__='reliability_metrics'; id=Column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4); equipment_id=Column(UUID(as_uuid=True),ForeignKey('equipment.id',ondelete='CASCADE'),nullable=False); calculated_at=Column(DateTime(timezone=True),default=datetime.utcnow); mtbf_hours=Column(Float); mttr_hours=Column(Float); availability_percent=Column(Float); failure_count=Column(Integer,default=0); downtime_hours=Column(Float,default=0); reliability_score=Column(Float); risk_score=Column(Float)
class ImportJob(Base):
 __tablename__='import_jobs'; id=Column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4); filename=Column(String(500),nullable=False); import_type=Column(String(100),nullable=False); status=Column(String(30),default='RECEIVED'); rows_read=Column(Integer,default=0); rows_created=Column(Integer,default=0); rows_updated=Column(Integer,default=0); rows_skipped=Column(Integer,default=0); errors=Column(JSONB,default=list); created_at=Column(DateTime(timezone=True),default=datetime.utcnow); completed_at=Column(DateTime(timezone=True))
class ComponentChange(Base):
 __tablename__='component_changes'; id=Column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4); equipment_id=Column(UUID(as_uuid=True),ForeignKey('equipment.id',ondelete='CASCADE'),nullable=False); changed_at=Column(DateTime(timezone=True),nullable=False); component_name=Column(String(255),nullable=False); old_component=Column(String(255)); new_component=Column(String(255)); reason=Column(Text); performed_by=Column(String(255)); sap_order_number=Column(String(100)); running_hours=Column(Float); source=Column(String(50),default='manual'); created_at=Column(DateTime(timezone=True),default=datetime.utcnow)
class Document(Base):
 __tablename__='documents'; id=Column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4); equipment_id=Column(UUID(as_uuid=True),ForeignKey('equipment.id',ondelete='SET NULL')); title=Column(String(500),nullable=False); document_type=Column(String(100)); source=Column(String(255)); file_path=Column(Text); content=Column(Text); metadata_json=Column('metadata',JSONB,default=dict); created_at=Column(DateTime(timezone=True),default=datetime.utcnow)
class DocumentChunk(Base):
 __tablename__='document_chunks'; id=Column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4); document_id=Column(UUID(as_uuid=True),ForeignKey('documents.id',ondelete='CASCADE'),nullable=False); chunk_index=Column(Integer,nullable=False); content=Column(Text,nullable=False); embedding=Column(Vector(768)); metadata_json=Column('metadata',JSONB,default=dict)
